### ISSUE TITLE
Code style

### ISSUE THREAD

**Issue by trampolinecall** [trampolinecall/uhf#24]
The current code style is manually maintained and is therefore rather inconsistent. Fixing this will probably end up involving a fair bit of work, but should also be helped by automated code formatting tools.

# TODOS

- [ ] Convert all monadic blocks with `>>=` and `>>` to do blocks
- [ ] Add configuration file for an autoformatter (fourmolu?)
- [ ] Figure out how to get the right version of the autoformatter (dev dependencies?)
