### ISSUE TITLE
Fully implement keyword calls

### ISSUE THREAD

**Issue by trampolinecall** [trampolinecall/uhf#34]
The keyword identifier token type was added in the parser overhaul (see PR #23), but almost none of the functionality has been implemented yet.

# TODO

- [x] Parse keyword calls (will be completed when #23 is merged)
- [ ] Make ASTs for keyword calls
- [ ] Keyword variables in patterns (also see #40)
- [ ] Plumb them through the rest of the compiler
